"""Add profile_picture, bio and preferred_language columns

Revision ID: 5af4e5d00804
Revises: cf97cbae2c98
Create Date: 2025-12-18 10:46:14.319887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5af4e5d00804'
down_revision: Union[str, None] = 'cf97cbae2c98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture', sa.String(length=500), nullable=True, comment='URL to profile picture'))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True, comment='User bio/description'))
    op.add_column('users', sa.Column('preferred_language', sa.String(length=10), nullable=False, comment='Language preference (en, hi, etc)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_language')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'profile_picture')
    # ### end Alembic commands ###
