"""Initial migration - user table with all features

Revision ID: cf97cbae2c98
Revises: 
Create Date: 2025-12-18 10:43:05.862023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf97cbae2c98'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_active_aadhaar', 'users', ['is_deleted', 'aadhaar'], unique=False)
    op.create_index('idx_active_email', 'users', ['is_deleted', 'email'], unique=False)
    op.create_index('idx_active_mobile', 'users', ['is_deleted', 'primary_mobile'], unique=False)
    op.create_index('idx_active_pan', 'users', ['is_deleted', 'pan'], unique=False)
    op.create_index('idx_created_at', 'users', ['created_at'], unique=False)
    op.create_index('idx_name_search', 'users', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_name_search', table_name='users')
    op.drop_index('idx_created_at', table_name='users')
    op.drop_index('idx_active_pan', table_name='users')
    op.drop_index('idx_active_mobile', table_name='users')
    op.drop_index('idx_active_email', table_name='users')
    op.drop_index('idx_active_aadhaar', table_name='users')
    # ### end Alembic commands ###
